export const industry_list = [
  {
    id: 7123478,
    name: "Accounting / Audit / Tax Services",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123479,
    name: "Advertising / Public Relations / Marketing Services",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123480,
    name: "Architecture / Building / Construction",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123481,
    name: "Athletics / Sports",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123482,
    name: "Charity / Social Services / Non- Profit Organization",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123483,
    name: "Chemical / Plastic / Paper / Petrochemical",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123484,
    name: "Civil Services (Government, Armed Forces)",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123485,
    name: "Clothing / Garment / Textiles",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123486,
    name: "Education",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123487,
    name: "Electronics / Electrical Equipment",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123488,
    name: "Energy / Power / Water / Oil & Gas / Waste Management",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123489,
    name: "Engineering - Building, Civil, Construction / Quantity Survey",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123490,
    name: "Engineering - Electrical / Electronics / Mechanical",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123491,
    name: "Engineering - Others",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123492,
    name: "Entertainment / Recreations",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123493,
    name: "Financial Services",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123494,
    name: "Food and Beverage / Catering",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123495,
    name: "Freight Forwarding / Delivery / Shipping",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123496,
    name: "General Business Services",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123497,
    name: "Health & Beauty Care",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123498,
    name: "Hospitality / Catering",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123499,
    name: "Human Resources Management / Consultancy",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123500,
    name: "Industrial Machinery / Automation Equipment",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123501,
    name: "Information Technology",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123502,
    name: "Insurance / Pension Funding",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123503,
    name: "Interior Design / Graphic Design",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123504,
    name: "Jewelry / Gems / Watches",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123505,
    name: "Laboratory",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123506,
    name: "Legal Services",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123507,
    name: "Management Consultancy / Services",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123508,
    name: "Manufacturing",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123509,
    name: "Mass Transportation",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123510,
    name: "Media / Publishing / Printing",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123511,
    name: "Medical / Pharmaceutical",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123512,
    name: "Mixed Industry Group",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123513,
    name: "Motor Vehicles",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123528,
    name: "Others",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123514,
    name: "Packaging",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123515,
    name: "Performance / Musical / Artistic",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123516,
    name: "Petroleum",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123517,
    name: "Property Development",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123518,
    name: "Property Management / Consultancy",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123519,
    name: "Public Utilities",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123520,
    name: "Research / Survey",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123521,
    name: "Security Escort",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123522,
    name: "Security / Fire / Electronic Access Controls",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123523,
    name: "Telecommunication",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123524,
    name: "Tourism / Travel Agency",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123525,
    name: "Toys",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123526,
    name: "Trading and Distribution",
    creator_name: "VizServe Private Limited",
  },
  {
    id: 7123527,
    name: "Wholesale / Retail",
    creator_name: "VizServe Private Limited",
  },
];

export const entity_list = [
  {
    id: 3779178,
    external_id: null,
    name: "HAPI HAUS",
    description: "",
    logo: "https://hfse.edu.sg/wp-content/uploads/2024/11/HapiHaus-Logo--1024x419.png",
    creator: 844366,
    owner: 844401,
    address: "",
    website: "https://hfse.edu.sg/hapi-haus/",
    is_public: true,
    is_visible: true,
    custom_fields: {},
    created_at: "2025-09-02T05:43:03.210691Z",
    updated_at: "2025-11-14T05:26:12.803190Z",
  },
  {
    id: 3779180,
    external_id: null,
    name: "HAPI SPACE",
    description: "",
    logo: "https://hfse.edu.sg/wp-content/uploads/2024/11/HapiSpace-Logo2222-1024x447.png",
    creator: 844366,
    owner: 844401,
    address: "",
    website: "https://hfse.edu.sg/hapi-space/",
    is_public: true,
    is_visible: true,
    custom_fields: {},
    created_at: "2025-09-02T05:46:22.885772Z",
    updated_at: "2025-11-14T05:26:12.803190Z",
  },
  {
    id: 3779176,
    external_id: null,
    name: "HFSE Global Academy",
    description: "",
    logo: "https://hfse.edu.sg/wp-content/uploads/2024/12/HFSE-Global-ACADEMY-1024x893.png",
    creator: 844366,
    owner: 844401,
    address: "",
    website: "https://hfse.edu.sg/hfse-global-academy/",
    is_public: true,
    is_visible: true,
    custom_fields: {},
    created_at: "2025-09-02T05:40:54.245031Z",
    updated_at: "2025-11-14T05:26:12.803190Z",
  },
  {
    id: 3779172,
    external_id: null,
    name: "HFSE International School",
    description: "",
    logo: "https://enrol.hfse.edu.sg/assets/hfse-logo-DkPrMQiq.webp",
    creator: 844366,
    owner: 844401,
    address: "",
    website: "https://isa.hfse.edu.sg/",
    is_public: true,
    is_visible: true,
    custom_fields: {},
    created_at: "2025-09-02T05:37:05.001059Z",
    updated_at: "2025-11-14T05:26:12.803190Z",
  },
  {
    id: 3779173,
    external_id: null,
    name: "HFSE YoungStarters",
    description: "",
    logo: "https://hfse.edu.sg/wp-content/uploads/2025/02/YS-LOGO_no-startthemyoung_white-1024x747.png",
    creator: 844366,
    owner: 844401,
    address: "",
    website: "https://hfse.edu.sg/hfse-youngstarters/",
    is_public: true,
    is_visible: true,
    custom_fields: {},
    created_at: "2025-09-02T05:38:46.815985Z",
    updated_at: "2025-11-14T05:26:12.803190Z",
  },
  {
    id: 3779179,
    external_id: null,
    name: "Our HAPI Co.",
    description: "",
    logo: "https://hfse.edu.sg/wp-content/uploads/2025/02/HapiCo-Logo_2-1021x1024.png",
    creator: 844366,
    owner: 844401,
    address: "",
    website: "https://hfse.edu.sg/our-hapi-co/",
    is_public: true,
    is_visible: true,
    custom_fields: {},
    created_at: "2025-09-02T05:43:56.855631Z",
    updated_at: "2025-11-14T05:26:12.803190Z",
  },
  {
    id: 3779177,
    external_id: null,
    name: "VizSchool",
    description: "",
    logo: "https://hfse.edu.sg/wp-content/uploads/2024/11/VIZSCHOOL-LOGO-WHITE-BG-400pxy.png",
    creator: 844366,
    owner: 844401,
    address: "",
    website: "https://vizschool.org/",
    is_public: true,
    is_visible: true,
    custom_fields: {},
    created_at: "2025-09-02T05:42:09.089757Z",
    updated_at: "2025-11-14T05:26:12.803190Z",
  },
];
